// <auto-generated by="the Blazor I18n Text compiler" />
namespace MyNameSpace.Components.I18nText.Shared
{
    public partial class NavMenu : global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage, global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextLateBinding
    {
        string global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage.FallBackLanguage => "en";

        public string this[string key] => global::Toolbelt.Blazor.I18nText.I18nTextExtensions.GetFieldValue(this, key);

        /// <summary>"The demonstration of how to localize data annotations validation error messages by using &quot;LocalizedDataAnnotationsValidator&quot; on Server-side Blazor app"</summary>
        public string Description;

        /// <summary>"&quot;LocalizedDataAnnotationsValidator&quot; - Live Demo"</summary>
        public string SiteName;
    }
}
