// <auto-generated by="the Blazor I18n Text compiler" />
namespace MyNameSpace.Components.I18nText.Models
{
    public partial class Person : global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage, global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextLateBinding
    {
        string global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage.FallBackLanguage => "en";

        public string this[string key] => global::Toolbelt.Blazor.I18nText.I18nTextExtensions.GetFieldValue(this, key);

        /// <summary>"Name"</summary>
        public string Name;

        /// <summary>"The {0} field is required."</summary>
        public string Required;

        /// <summary>"{0} is too long."</summary>
        public string TooLong;
    }
}
