// <auto-generated by="the Blazor I18n Text compiler" />
namespace MyNameSpace.Components.I18nText.Pages
{
    public partial class Index : global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage, global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextLateBinding
    {
        string global::Toolbelt.Blazor.I18nText.Interfaces.I18nTextFallbackLanguage.FallBackLanguage => "en";

        public string this[string key] => global::Toolbelt.Blazor.I18nText.I18nTextExtensions.GetFieldValue(this, key);

        /// <summary>"Do Validation"</summary>
        public string DoValidation;

        /// <summary>"Name (required, up to 10 characters.)"</summary>
        public string LabelForName;
    }
}
